### ISSUE TITLE
"Strg" doesn't work in English

### ISSUE THREAD

**Issue by mp108** [gueggel/SJ.Buzzer#1]
As described here, "Strg" needs to be "Control" to work in other languages:
https://stackoverflow.com/questions/59245734/language-problems-with-shortcuts-in-resx-files

**Comment by gueggel** [comment]
Thank you. Confirmed and fixed. I now set the shortcut keys inside the code and not with the resource file. Look at af82a14237c66575962cc5e658e59330df857fbe
